### ISSUE TITLE
Beast Training does not work

### ISSUE THREAD

**Issue by Digawen** [Beast-Masters-addons/HuntersHelper#1]
3x GFW_HuntersHelper\addon\HHSpells.lua:30: attempt to index field 'knownSpells' (a nil value)
[string "@GFW_HuntersHelper\addon\HHSpells.lua"]:30: in function `isSpellKnown'
[string "@GFW_HuntersHelper\HuntersHelper.lua"]:635: in function `FHH_CurrentZoneLearnableBeasts'
[string "@GFW_HuntersHelper\HuntersHelper.lua"]:333: in function `FHH_MinimapUpdateCount'
[string "@GFW_HuntersHelper\HuntersHelper.lua"]:459: in function `FHH_ScanCraftFrame'
[string "@GFW_HuntersHelper\HuntersHelper.lua"]:141: in function `FHH_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
self = <table> {
 hunterKnowSpell = <function> defined @GFW_HuntersHelper\addon\HHSpells.lua:23
 saveCurrentPetSpells = <function> defined @GFW_HuntersHelper\addon\HHSpells.lua:41
 scanCraftFrame = <function> defined @GFW_HuntersHelper\addon\HHSpells.lua:9
 saveKnownSpell = <function> defined @GFW_HuntersHelper\addon\HHSpells.lua:13
 buildSpellList = <function> defined @GFW_HuntersHelper\addon\HHSpells.lua:48
 isSpellKnown = <function> defined @GFW_HuntersHelper\addon\HHSpells.lua:29
 getHighestKnownRank = <function> defined @GFW_HuntersHelper\addon\HHSpells.lua:72
}
icon = "ability_racial_cannibalize"
rank = 8
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "attempt to index field 'knownSpells' (a nil value)"

**Comment by Digawen** [comment]
3x GFW_HuntersHelper\addon\HHSpells.lua:74: attempt to index field 'knownSpells' (a nil value)
[string "@GFW_HuntersHelper\addon\HHSpells.lua"]:74: in function `getHighestKnownRank'
[string "@GFW_HuntersHelperUI\HuntersHelperUI.lua"]:262: in function `FHH_UISpellAndRankStatus'
[string "@GFW_HuntersHelperUI\HuntersHelperUI.lua"]:252: in function `FHH_UISpellStatus'
[string "@GFW_HuntersHelperUI\HuntersHelperUI.lua"]:241: in function `FHH_GenerateListItem'
[string "@GFW_HuntersHelper\addon\HHSpells.lua"]:63: in function `buildSpellList'
[string "@GFW_HuntersHelperUI\HuntersHelperUI.lua"]:193: in function `FHH_UIUpdateList'
[string "@GFW_HuntersHelperUI\HuntersHelperUI.lua"]:61: in function `FHH_UIOnShow'
[string "*:OnShow"]:2: in function <[string "*:OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2555: in function <FrameXML\UIParent.lua:2541>
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@GFW_HuntersHelper\HuntersHelper.lua"]:143: in function `FHH_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
self = <table> {
 hunterKnowSpell = <function> defined @GFW_HuntersHelper\addon\HHSpells.lua:23
 saveCurrentPetSpells = <function> defined @GFW_HuntersHelper\addon\HHSpells.lua:41
 scanCraftFrame = <function> defined @GFW_HuntersHelper\addon\HHSpells.lua:9
 saveKnownSpell = <function> defined @GFW_HuntersHelper\addon\HHSpells.lua:13
 buildSpellList = <function> defined @GFW_HuntersHelper\addon\HHSpells.lua:48
 isSpellKnown = <function> defined @GFW_HuntersHelper\addon\HHSpells.lua:29
 getHighestKnownRank = <function> defined @GFW_HuntersHelper\addon\HHSpells.lua:72
}
icon = "inv_weapon_shortblade_28"
highest = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'knownSpells' (a nil value)"



**Second Lua Error ( after installing Lib: HunterPetInfo)**

**Comment by datagutten** [comment]
I had trouble reproducing this, but after a visit to the pet trainer, the error suddenly appeared. I discovered that Cobra Reflexes has no rank and stopped the scan for learned spells. I am working on a fix.
