### ISSUE TITLE
another lua error (still not usable for me) version 4.0.3

### ISSUE THREAD

**Issue by Digawen** [Beast-Masters-addons/HuntersHelper#2]
4x GFW_HuntersHelper\HuntersHelper.lua:797: Unknown source unknown
[string "=[C]"]: in function `error'
[string "@GFW_HuntersHelper\HuntersHelper.lua"]:797: in function `FHH_SpellHasLearnableBeasts'
[string "@GFW_HuntersHelperUI\HuntersHelperUI.lua"]:293: in function `FHH_UISpellAndRankStatus'
[string "@GFW_HuntersHelperUI\HuntersHelperUI.lua"]:252: in function `FHH_UISpellStatus'
[string "@GFW_HuntersHelperUI\HuntersHelperUI.lua"]:241: in function `FHH_GenerateListItem'
[string "@GFW_HuntersHelper\addon\HHSpells.lua"]:82: in function `buildSpellList'
[string "@GFW_HuntersHelperUI\HuntersHelperUI.lua"]:193: in function `FHH_UIUpdateList'
[string "@GFW_HuntersHelperUI\HuntersHelperUI.lua"]:61: in function `FHH_UIOnShow'
[string "*:OnShow"]:2: in function <[string "*:OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2565: in function <FrameXML\UIParent.lua:2551>
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@GFW_HuntersHelper\HuntersHelper.lua"]:143: in function `FHH_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
(*temporary) = "Unknown source unknown"

AND

3x ...rfaceGFW_HuntersHelperUI\HuntersHelperUI.lua:962: Spell is not set on button
[string "=[C]"]: in function `assert'
[string "@GFW_HuntersHelperUI\HuntersHelperUI.lua"]:962: in function `FHH_UIRankButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = nil
(*temporary) = "Spell is not set on button"

**Comment by datagutten** [comment]
Which level is your hunter? I am not able to reproduce it on my hunter, but it might be too low level to learn the spell causing problems. #3 changed the lua error to a nicer error printed in chat and I will also push another change to handle spells with unknown source.
